version: '3'
services:
  currency-exchange-service:
    image: tomek371240/currency-exchange-service:5
    networks:
      - springcloud-overlay
#    ports:
#      - "8000:8000"
  currency-conversion-service:
    image: tomek371240/currency-conversion-service:4
    networks:
      - springcloud-overlay
#    ports:
#      - "8100:8100"
  netflix-zuul-api-gateway-server:
    image: tomek371240/netflix-zuul-api-gateway-server:4
    networks:
      - springcloud-overlay
    ports:
      - "8765:8765"
networks:
  springcloud-overlay:
    external:
      name: springcloud-overlay